### ISSUE TITLE
Legacy plugin invocation does not work correctly. The cyloneDx Plugin can not be found and applied in this case.

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [Liftric/dependency-track-companion-plugin#7]
In some of our projects we are bound to the legacy plugin invocation due to some restrictions of the plugin DSL. When I tried to use this approach also for the dependency-track-companion-plugin I'll get an error from gradle that it could not find the cycloneDX plugin. I assume that there is something missing in this case. Either there is a bug in the code or there is some configuration missing from the documentation.

Here the message:

```
* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin class 'com.liftric.dtcp.DepTrackCompanionPlugin'.
   > Plugin with id 'org.cyclonedx.bom' not found.

```

**Comment by ManfredSchenkIOSB** [comment]
Also from a perspective of clean coding, i.e. the statements on "using implicit dependencies" it is bad practise to apply a plugin from within another plugin. see also: https://marcelkliemannel.com/articles/2022/common-gradle-plugin-mistakes-and-good-practices/#dont-apply-other-plugins

**Comment by ManfredSchenkIOSB** [comment]
if I switch back to version 1.0.1 of your plugin and apply the cyclonedx plugin by myself then it works. So it is one of the latest commits which brakes my build by applying the plugin internally.

**Comment by nvima** [comment]
I'm sorry you have problems with the last updates and I haven't answered here for so long.
I agree with you that it is not clean code when I apply the plugin in my plugin.
I will check with work colleagues and work on a solution for this, probably as suggested we will not apply the CyclonDx plugin itself.

**Comment by ManfredSchenkIOSB** [comment]
Did you already come to a decision about this issue?

**Comment by nvima** [comment]
i have spoken to my colleagues at work, and unfortunately we cannot implement this at the moment, as it would mean that we would have to adapt the configuration in all projects.
But thank you for the details on best practices, I really liked the blog article and will keep it in mind in the future.
You are free to fork the project and remove the plugin.
thank you for your understanding
